title: "Banchetti Prc Piemonte"
description: ""
url: "https://prcpiemonte.github.io/referendum" # the base hostname & protocol for your site
locale: "it"


markdown: kramdown
future: true
destination: _site
sass:
    sass_dir: _sass
include: ['_pages']