title: "10èilminimo"
description: ""
url: "https://10ilminimo.github.io" # the base hostname & protocol for your site
locale: "it"


markdown: kramdown
future: true
destination: _site
sass:
    sass_dir: _sass
include: ['_pages']